document.writeln("<!DOCTYPE html");
document.writeln("<head>");
document.writeln("<style>");
document.writeln("</style>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("<title></title>");
document.writeln("</head>");
document.writeln("<body >");
document.writeln("<header>");
document.writeln("<div class='nav'>");
document.writeln("<a class = 'nav_1' href='http://yunpaas.jvtd.cn/index.html'><img src='"+path+"/homePage/images/logo.png'></a>");
document.writeln("<div class='nav_2'>");
document.writeln("<ul>");
document.writeln("<li><a href='http://yunpaas.jvtd.cn/index.html'>首页</a></li>");
document.writeln("<li class='navnav'><a class='heng' href='javascript:;'>产品介绍</a>");
document.writeln("<div class='xiala'><div class='box'><div class='caidan clearfix'><div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/SMS1.html'>【短信】</a></div>");
document.writeln("<ul><li><a href='http://yunpaas.jvtd.cn/dxyzm.html'>短信验证码</a></li><li><a href='http://yunpaas.jvtd.cn/dxtztd.html'>营销短信</a></li><li><a href='http://yunpaas.jvtd.cn/yyyzm.html'>语音验证码</a></li><li><a href='http://yunpaas.jvtd.cn/gjdx.html'>国际短信</a></li><li><a href='http://yunpaas.jvtd.cn/dxgzh.html'>短信公众号</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/yuyin.html'>【语音】</a></div>");
document.writeln("<ul><li><a href='http://yunpaas.jvtd.cn/yyth.html'>语音通话</a></li><li><a href='http://yunpaas.jvtd.cn/dhhy.html'>电话会议</a></li><li><a href='http://yunpaas.jvtd.cn/dhhb.html'>电话回拨</a></li><li><a href='http://yunpaas.jvtd.cn/yytz.html'>语音通知</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/sssp.html'>【视频】</a></div><ul><li><a href='http://yunpaas.jvtd.cn/sssp.html'>音视频通话</a></li><li><a href='http://yunpaas.jvtd.cn/sssp.html'>音视频会议</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/chanpingim.html'>【IM即时信息】</a></div><ul><li><a href='http://yunpaas.jvtd.cn/chanpingim.html'>单聊</a></li><li><a href='http://yunpaas.jvtd.cn/chanpingim.html'>群聊</a></li><li><a href='http://yunpaas.jvtd.cn/chanpingim.html'>IM客服</a></li></ul></div><div class='box_1'>");
document.writeln("<div class='name'><a href='http://yunpaas.jvtd.cn/zzfw.html'>【增值服务】</a></div><ul><li><a href='http://yunpaas.jvtd.cn/llcz.html'>流量充值</a></li><li><a href='http://yunpaas.jvtd.cn/hfcz.html'>话费充值</a></li></ul>");
document.writeln("</div></div></div></div></li>");
document.writeln("<li class='navnav'><a href='javascript:;'>解决方案</a><div class='xiala2'><div class='box'><div class='caidan clearfix'><div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/hjzx.html'>呼叫中心</a></div></div><div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/qyzj.html'>企业总机</a></div></div><div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/dhyx.html'>电话营销</a></div></div><div class='box_1'><div class='name'><a href='http://yunpaas.jvtd.cn/ssll.html'>嗖嗖流量</a></div></div></div></div></div></li>");
document.writeln("<li><a href='http://yunpaas.jvtd.cn/jg.html'>价格</a></li>");
document.writeln("<li class='navnav'><a href='http://yunpaas.jvtd.cn/gsjs.html'>关于我们</a><div class='xiala1'><div class='box'><div class='caidan clearfix'><div class='box_1'><!-- <div class='name'><a href='ytxyx.html'>短信</a></div>--><ul><li><a href='http://yunpaas.jvtd.cn/gsjs.html'>公司介绍</a></li><li><a href='http://yunpaas.jvtd.cn/lxwm.html'>联系我们</a></li><li><a href='http://yunpaas.jvtd.cn/fwal.html'>服务案例</a></li><li><a href='http://yunpaas.jvtd.cn/jstd.html'>技术团队</a></li><li><a href='http://yunpaas.jvtd.cn/qydt.html'>新闻中心</a></li><li><a href='http://yunpaas.jvtd.cn/bghj.html'>办公环境</a></li><li><a href='http://yunpaas.jvtd.cn/fzlc.html'>发展历程</a></li><li><a href='http://yunpaas.jvtd.cn/jrwm.html'>加入我们</a></li></ul></div></div></div></div></li><li class='navnav'><a href='http://yunpaas.jvtd.cn/mfty.html'>免费体验</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<div class='nav_13'><a href='/admin/login.do'>登陆</a><a href='/admin/register.do'>注册</a></div>");
document.writeln("</div>");
document.writeln("</header>");
document.writeln(" ");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
