document.writeln("<!DOCTYPE html");
document.writeln("<head>");
document.writeln("<style>");
document.writeln("</style>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
document.writeln("<title></title>");
document.writeln("</head>");
document.writeln("<body >");
document.writeln("<header>");
document.writeln("<div class='nav'>");
document.writeln("<a class = 'nav_1' href='/index.html'><img src='"+path+"/homePage/images/logo.png'></a>");
document.writeln("<div class='nav_2'>");
document.writeln("<ul>");
document.writeln("<li><a href='"+path+"/homePage/indexPage.jsp'>首页</a></li>");
document.writeln("<li class='navnav'><a href='javascript:;'>产品介绍</a>");
document.writeln("<div class='xiala'><div class='box'><div class='caidan clearfix'><div class='box_1'><div class='name'><a  href='"+path+"/homePage/SMS1.jsp'>【短信】</a></div>");
document.writeln("<ul><li><a href='"+path+"/homePage/dxyzm.jsp'>短信验证码</a></li><li><a href='"+path+"/homePage/dxtztd.jsp'>营销短信</a></li><li><a href='"+path+"/homePage/yyyzm.jsp'>语音验证码</a></li><li><a href='"+path+"/homePage/gjdx.jsp'>国际短信</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='"+path+"/homePage/yuyin.jsp'>【语音】</a></div>");
document.writeln("<ul><li><a href='"+path+"/homePage/yyth.jsp'>语音通话</a></li><li><a href='"+path+"/homePage/dhhy.jsp'>电话会议</a></li><li><a href='"+path+"/homePage/dhhb.jsp'>电话回拨</a></li><li><a href='"+path+"/homePage/yytz.jsp'>语音通知</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='"+path+"/homePage/sssp.jsp'>【视频】</a></div><ul><li><a href='"+path+"/homePage/sssp.jsp'>音视频通话</a></li><li><a href='"+path+"/homePage/sssp.jsp'>音视频会议</a></li></ul></div>");
document.writeln("<div class='box_1'><div class='name'><a href='"+path+"/homePage/chanpingim.jsp'>【IM即时信息】</a></div><ul><li><a href='"+path+"/homePage/chanpingim.jsp'>单聊</a></li><li><a  href='"+path+"/homePage/chanpingim.jsp'>群聊</a></li><li><a href='"+path+"/homePage/chanpingim.jsp'>IM客服</a></li></ul></div><div class='box_1'>");
document.writeln("<div class='name'><a href='"+path+"/homePage/zzfw.jsp'>【增值服务】</a></div><ul><li><a href='"+path+"/homePage/llcz.jsp'>流量充值</a></li><li><a href='"+path+"/homePage/hhcz.jsp'>话费充值</a></li></ul>");
document.writeln("</div></div></div></div></li>");
document.writeln("<li class='navnav'><a href='javascript:;'>解决方案</a><div class='xiala2'><div class='box'><div class='caidan clearfix'><div class='box_1'><div class='name'><a href='"+path+"/homePage/hjzx.jsp'>呼叫中心</a></div></div><div class='box_1'><div class='name'><a href='"+path+"/homePage/qyzj.jsp'>企业总机</a></div></div><div class='box_1'><div class='name'><a href='"+path+"/homePage/dhyx.jsp'>电话营销</a></div></div><div class='box_1'><div class='name'><a href='"+path+"/homePage/ssll.jsp'>嗖嗖流量</a></div></div></div></div></div></li>");
document.writeln("<li><a href='"+path+"/homePage/price.jsp'>价格</a></li>");
document.writeln("<li class='navnav'><a  href='"+path+"/homePage/gsjs.jsp'>关于我们</a><div class='xiala1'><div class='box'><div class='caidan clearfix'><div class='box_1'><!--<div class='name'><a href='ytxyx.html'>短信</a></div>--><ul><li><a href='"+path+"/homePage/gsjs.jsp'>公司介绍</a></li><li><a href='"+path+"/homePage/lxwm.jsp'>联系我们</a></li><li><a href='"+path+"/homePage/fwal.jsp'>服务案例</a></li><li><a href='"+path+"/homePage/jstd.jsp'>技术团队</a></li><li><a href='"+path+"/homePage/qydt.jsp'>新闻中心</a></li><li><a href='"+path+"/homePage/bghj.jsp'>办公环境</a></li><li><a href='"+path+"/homePage/fzlc.jsp'>发展历程</a></li><li><a href='"+path+"/homePage/jrwm.jsp'>加入我们</a></li></ul></div></div></div></div></li><li class='navnav'><a class='heng' href='"+path+"/homePage/mfty.jsp'>免费体验</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
//document.writeln("<div class='nav_13'><a href='/admin/login.do'>登陆</a><a href='/admin/register.do'>注册</a></div>");
document.writeln("</div>");
document.writeln("</header>");
document.writeln(" ");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");
